packages:
  - apps/*
  - packages/*

catalog:
  "@base-ui/react": ^1.4.1
  "@kyh/tsconfig": ^1.1.14
  "@tailwindcss/postcss": ^4.2.4
  "@tanstack/react-query": ^5.100.8
  "@trpc/client": ^11.17.0
  "@trpc/server": ^11.17.0
  "@trpc/tanstack-react-query": ^11.17.0
  "@types/node": ^25.6.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  next: ^16.2.4
  react: ^19.2.5
  react-dom: ^19.2.5
  superjson: ^2.2.6
  typescript: ^6.0.3
  zod: ^4.4.2
