packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.13
  "@kyh/prettier-config": ^1.1.13
  "@kyh/tsconfig": ^1.1.13
  "@tanstack/react-query": ^5.90.21
  "@trpc/client": ^11.10.0
  "@trpc/server": ^11.10.0
  "@trpc/tanstack-react-query": ^11.10.0
  "@types/node": ^25.2.3
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  eslint: ^9.39.2
  next: ^16.1.6
  prettier: ^3.8.1
  react: ^19.2.4
  react-dom: ^19.2.4
  superjson: ^2.2.6
  typescript: ^5.9.3
  zod: ^4.3.6

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
