packages:
  - apps/*
  - packages/*

catalog:
  "eslint": 9.14.0
  "prettier": ^3.3.3
  "typescript": ^5.6.3
  "zod": ^3.23.8
  "tailwindcss": ^3.4.15
  "react": ^18.3.1
  "react-dom": ^18.3.1
  "next": ^15.0.3
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@types/node": ^22.9.1
  "@kyh/eslint-config": ^1.1.0
  "@kyh/prettier-config": ^1.1.0
  "@kyh/tsconfig": ^1.1.0
  "@tanstack/react-query": ^5.60.6
  "@tanstack/react-query-devtools": ^5.60.6
  "@trpc/client": ^11.0.0-rc.593
  "@trpc/react-query": ^11.0.0-rc.593
  "@trpc/server": ^11.0.0-rc.593
