packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.3
  "@kyh/prettier-config": ^1.1.3
  "@kyh/tsconfig": ^1.1.3
  "@tanstack/react-query-devtools": ^5.64.0
  "@tanstack/react-query": ^5.64.0
  "@trpc/client": ^11.0.0-rc.593
  "@trpc/react-query": ^11.0.0-rc.593
  "@trpc/server": ^11.0.0-rc.593
  "@types/node": ^22.10.5
  "@types/react-dom": ^19.0.2
  "@types/react": ^19.0.4
  "eslint": ^9.18.0
  "next": ^15.1.4
  "prettier": ^3.4.2
  "react-dom": ^19.0.0
  "react": ^19.0.0
  "superjson": "2.2.2"
  "tailwindcss": ^3.4.17
  "typescript": ^5.7.3
  "zod": ^3.24.1
