packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.13
  "@kyh/prettier-config": ^1.1.13
  "@kyh/tsconfig": ^1.1.13
  "@tanstack/react-query": ^5.90.19
  "@trpc/client": ^11.8.1
  "@trpc/server": ^11.8.1
  "@trpc/tanstack-react-query": ^11.8.1
  "@types/node": ^24.10.9
  "@types/react": ^19.2.9
  "@types/react-dom": ^19.2.3
  eslint: ^9.39.2
  next: ^16.1.4
  prettier: ^3.8.1
  react: ^19.2.3
  react-dom: ^19.2.3
  superjson: ^2.2.6
  typescript: ^5.9.3
  zod: ^4.3.5

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
