packages:
  - apps/*
  - packages/*

catalog:
  eslint: ^8.57.0
  prettier: ^3.3.2
  typescript: ^5.5.4
  zod: ^3.23.8
  tailwindcss: ^3.4.7
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@types/node": ^22.1.0
  "@kyh/eslint-config": ^0.1.9
  "@kyh/prettier-config": ^0.1.9
  "@kyh/tsconfig": ^0.1.9
  "@tanstack/react-query": ^5.51.21
  "@trpc/client": ^11.0.0-rc.466
  "@trpc/react-query": ^11.0.0-rc.466
  "@trpc/server": ^11.0.0-rc.466
