packages:
  - apps/*
  - packages/*

catalog:
  # Dev tooling
  "@kyh/eslint-config": ^1.1.6
  "@kyh/prettier-config": ^1.1.6
  "@kyh/tsconfig": ^1.1.6
  "@types/node": ^22.15.33
  "@types/react-dom": ^19.1.6
  "@types/react": ^19.1.8
  "eslint": ^9.29.0
  "prettier": ^3.6.1
  "typescript": ^5.8.3

  # API
  "@tanstack/react-query": ^5.81.2
  "@trpc/client": ^11.4.2
  "@trpc/tanstack-react-query": ^11.4.2
  "@trpc/server": ^11.4.2

  # Misc
  "superjson": "2.2.2"
  "zod": ^3.25.67

  # Client
  "next": ^15.3.4
  "react-dom": ^19.1.0
  "react": ^19.1.0
