packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.10
  "@kyh/prettier-config": ^1.1.10
  "@kyh/tsconfig": ^1.1.10
  "@tanstack/react-query": ^5.90.12
  "@trpc/client": ^11.7.2
  "@trpc/server": ^11.7.2
  "@trpc/tanstack-react-query": ^11.7.2
  "@types/node": ^24.10.3
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  eslint: ^9.39.1
  next: ^16.0.10
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  superjson: ^2.2.6
  typescript: ^5.9.3
  zod: ^4.1.13
