packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.7
  "@kyh/prettier-config": ^1.1.7
  "@kyh/tsconfig": ^1.1.7
  "@tanstack/react-query": ^5.87.1
  "@trpc/client": ^11.5.1
  "@trpc/server": ^11.5.1
  "@trpc/tanstack-react-query": ^11.5.1
  "@types/node": ^24.3.1
  "@types/react": ^19.1.12
  "@types/react-dom": ^19.1.9
  eslint: ^9.35.0
  next: ^15.5.2
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  superjson: ^2.2.2
  typescript: ^5.9.2
  zod: ^4.1.5
