// Since we used to use Prisma, these column values were generated by Prisma.
// Now that we're using Supabase, we need to generate these values ourselves.
import cuid from "cuid";

export const getCreateColumnValues = () => {
  const now = new Date();

  return {
    id: cuid(),
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  };
};

export const getUpdateColumnValues = () => {
  const now = new Date();

  return {
    updatedAt: now.toISOString(),
  };
};
