version: "3.8"

services:
  mysql:
    container_name: dev_mysql_container
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DB: dev

  maildev:
    container_name: dev_maildev_container
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
