import assert from "node:assert/strict";
import test from "node:test";

import {
  getExpiryProgress,
  getLegacyAvatarIndex,
  getReadingTime,
  parseServerDate,
  POST_EXPIRY_DAYS,
} from "./content.ts";

// --- Avatar mapping ---------------------------------------------------------

test("legacy avatar mapping is stable — DO NOT change these expected values", () => {
  // These are GOLDEN values, generated by running the real function. The project
  // decision doc states: "Preserve existing avatar mapping; changing modulus would
  // reshuffle users." If this test fails, you have reassigned every anonymous user's
  // avatar. Do NOT update the expectations to make it pass — revert the change to
  // getLegacyAvatarIndex.
  //
  // Note `hash &= hash` in the implementation looks like a no-op. It is not: it
  // coerces the accumulator to a 32-bit int. Removing it changes every value here.
  assert.equal(getLegacyAvatarIndex("Anonymous"), 7);
  assert.equal(getLegacyAvatarIndex(""), 0);
  assert.equal(getLegacyAvatarIndex("a"), 17);
  assert.equal(getLegacyAvatarIndex("A"), 5);
  assert.equal(getLegacyAvatarIndex("z"), 2);
  assert.equal(getLegacyAvatarIndex("日本語"), 3);
  assert.equal(getLegacyAvatarIndex("Kaiyu"), 15);
  assert.equal(getLegacyAvatarIndex("kaiyu"), 7);
  assert.equal(getLegacyAvatarIndex("user-1234"), 12);
  assert.equal(getLegacyAvatarIndex("🙂"), 5);
  assert.equal(getLegacyAvatarIndex("The quick brown fox"), 9);
  assert.equal(getLegacyAvatarIndex("x".repeat(500)), 4);
});

test("legacy avatar mapping defaults to Anonymous", () => {
  assert.equal(getLegacyAvatarIndex(), getLegacyAvatarIndex("Anonymous"));
});

test("avatar index is always within range", () => {
  for (const value of ["", "a", "Anonymous", "日本語", "🙂", "x".repeat(500)]) {
    const index = getLegacyAvatarIndex(value);
    assert.ok(index >= 0 && index < 20, `${value} → ${index} out of range`);
  }
});

// --- Reading time -----------------------------------------------------------

test("reading time counts spaced words", () => {
  assert.deepEqual(getReadingTime("hello world"), {
    minutes: 0.01,
    words: 2,
    text: "1 min read",
  });
});

test("reading time counts each CJK character as a word", () => {
  assert.deepEqual(getReadingTime("日本語"), { minutes: 0.015, words: 3, text: "1 min read" });
});

test("reading time mixes CJK and spaced words", () => {
  // "hello" + "world" (2 spaced) + 3 CJK characters = 5 words.
  assert.deepEqual(getReadingTime("hello 日本語 world"), {
    minutes: 0.025,
    words: 5,
    text: "1 min read",
  });
});

test("empty and whitespace-only text read as zero", () => {
  assert.deepEqual(getReadingTime(""), { minutes: 0, words: 0, text: "0 min read" });
  assert.deepEqual(getReadingTime("   "), { minutes: 0, words: 0, text: "0 min read" });
});

test("reading time is words / 200 minutes, rounded up for display", () => {
  assert.deepEqual(getReadingTime("word ".repeat(200)), {
    minutes: 1,
    words: 200,
    text: "1 min read",
  });
  assert.equal(getReadingTime("word ".repeat(201)).text, "2 min read");
});

// --- Server date parsing ----------------------------------------------------

test("zone-less server timestamps are parsed as UTC, not local", () => {
  // This is THE regression (plan 011). A bare `new Date(s)` on a zone-less string
  // parses as LOCAL time; in any non-UTC timezone that yields a different instant.
  // Run this suite under TZ=Asia/Tokyo to prove it.
  assert.equal(
    parseServerDate("2026-07-09 18:23:45.123").toISOString(),
    "2026-07-09T18:23:45.123Z",
  );
});

test("explicit zones are respected, not double-shifted", () => {
  assert.equal(
    parseServerDate("2026-07-09T18:23:45.123Z").toISOString(),
    "2026-07-09T18:23:45.123Z",
  );
  assert.equal(
    parseServerDate("2026-07-09T18:23:45.123+09:00").toISOString(),
    "2026-07-09T09:23:45.123Z",
  );
});

test("date-only strings parse as UTC midnight", () => {
  assert.equal(parseServerDate("2026-07-09").toISOString(), "2026-07-09T00:00:00.000Z");
});

// --- Expiry progress --------------------------------------------------------

test("a fresh letter is at 0% and not expired", () => {
  const now = new Date("2026-07-09T18:23:45.123Z");
  const progress = getExpiryProgress("2026-07-09 18:23:45.123", now);
  assert.equal(progress.percentage, 0);
  assert.equal(progress.isExpired, false);
  assert.equal(progress.start.toISOString(), "2026-07-09T18:23:45.123Z");
  assert.equal(progress.end.toISOString(), "2026-07-30T18:23:45.123Z");
});

test("the expiry window is exactly POST_EXPIRY_DAYS long", () => {
  const progress = getExpiryProgress("2026-07-09 00:00:00.000", new Date("2026-07-09T00:00:00Z"));
  const days = (progress.end.getTime() - progress.start.getTime()) / 86_400_000;
  assert.equal(days, POST_EXPIRY_DAYS);
});

test("halfway through the window reads 50%", () => {
  const start = Date.UTC(2026, 6, 9);
  const now = new Date(start + (POST_EXPIRY_DAYS / 2) * 86_400_000);
  assert.equal(getExpiryProgress("2026-07-09 00:00:00.000", now).percentage, 50);
});

test("percentage is clamped and expiry is flagged past the window", () => {
  const now = new Date("2026-08-30T00:00:00.000Z"); // well past 21 days
  const progress = getExpiryProgress("2026-07-09 18:23:45.123", now);
  assert.equal(progress.percentage, 100); // clamped, never 105
  assert.equal(progress.isExpired, true);
});

test("percentage is clamped at 0 for a future-dated letter", () => {
  const now = new Date("2026-07-01T00:00:00.000Z");
  const progress = getExpiryProgress("2026-07-09 00:00:00.000", now);
  assert.equal(progress.percentage, 0);
  assert.equal(progress.isExpired, false);
});

test("expiry is exclusive at the exact boundary instant", () => {
  const progress = getExpiryProgress("2026-07-09 00:00:00.000", new Date("2026-07-30T00:00:00Z"));
  assert.equal(progress.isExpired, true);
  assert.equal(progress.percentage, 100);
});
