-- drizzle-kit does not see Supabase's `auth` schema (drizzle.config.ts sets
-- schemaFilter: ["public"]), so it believes `auth.users` is an orphan and emits
-- DDL for it. Migration 0001 has the mirror image of this artifact commented out
-- for the same reason. Applying it would destroy Supabase Auth. NEVER uncomment.
-- DROP TABLE "auth"."users" CASCADE;
--> statement-breakpoint
-- Session revocation, NOT expiry. `DEFAULT 0 NOT NULL` on modern Postgres stores
-- the default in the catalog: no table rewrite, no long lock, and every existing
-- row reads back as 0 — which is exactly what a session cookie minted before this
-- column existed (no `epoch` field) is interpreted as. No user is logged out.
ALTER TABLE "User" ADD COLUMN "sessionEpoch" integer DEFAULT 0 NOT NULL;
